language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/516/9FONea-GLWhZC5VR6mJxlh01

env:
  global:
    - secure: "ZU/hX90HgX713ZBykUt494KVrLVgSBZRy5DrQwCf5qc1n8cGLm4MAbPuq6Kb/nUEECJt584xhdp/tzHUMPsIeqP+PjhhyvKCyVZV4LBwV7n2e9DT4qUkH1E2Ngl8qfZbvuqw/1DQ54UWms9DE0nenNhrXWGi/eraw5lwbGMMYss="
    - secure: "OZuRAxpz5n9Dq84FdokFSPju3gKqltLWjyOe/Ng0+eNt4LvMn6tcUk4PbEXY5yBFgGoj2ht/cOJ4ApQ1GWlUfKzMoYjC344C1Gu7+e+rOBFSmJXCtlp5qKx3bBebWAhwYQ/eS34plHQw53CI4lzhCYKv3YBdNSSYf93xfr0ZDVk="
